version: 2
jobs:
  build:
    docker:
      - image: composer:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-cache

      - run:
          name: composer-update
          command: composer update

      - save_cache:
          key: composer-cache
          paths:
            - $HOME/.composer/cache

      - run:
          name: create artifact zip
          command: |
            apk --no-cache add zip
            zip -r /tmp/artifact.zip ./web

      - store_artifacts:
          path: /tmp/artifact.zip
